version: '3.8'

services:
  # Service avec l'image odoo-ee-base
  odoo-base:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.odooEEbase
      args:
        - ODOO_DEB_PATH=./odoo_18.0+e.latest_all.deb
    image: ghcr.io/maelcatteau/odoo-ee-base:18.0
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8069"
      - "8072"
    networks:
      - odoo-network
      - npm-odoo
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./custom-addons:/mnt/extra-addons:delegated
      - ./config:/etc/odoo:z
      - odoo-data-base:/var/lib/odoo
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - ADMIN_PASSWORD=admin
      - PROXY_MODE=True
      - WEBSITE_SERVER_URL=https://activites.mcommemedoc.fr
      - ODOO_RC=/etc/odoo/odoo.conf
    command: ["--config=/etc/odoo/odoo.conf"]
    restart: unless-stopped

  # Base de données pour l'image de base
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    networks:
      - odoo-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
  odoo-data-base:  # Volume dédié pour l'instance odoo-base

networks:
  default:
  odoo-network:
    driver: bridge
  npm-odoo:
    external: true 